// let data = [{
//     AddressLine1 : "Himmatnager", 
//     AddressLine2 : "amd", 
//     AddressLine3 : "gandhinagar",
//     assignments: [{title:"assigenment1",status:"done"}, {title:"assigenment1",status:"pending"}],
//     CitizenshipId: 123456789, 
//     CitizenshipLegislationCode: "123456",
//     CitizenshipStatus: "approved",
//     CitizenshipToDate: "12/03/2012", 
//     City: "Himmatnagar", 
//     CorrespondenceLanguage: "Gujarati", 
//     Country: "India", 
//     CreationDate: "04/05/2012", 
//     DateOfBirth: "04/04/1998", 
//     directReports: [{id:1,name:"ruchit patel"}, {id:1,name:"Ravi sadariya"}], 
//     DisplayName: "Ravi sadariya",
//     DriversLicenseExpirationDate: "01/01/2030", 
//     DriversLicenseIssuingCountry: "India", 
//     DriversLicenseId: 123456, 
//     EffectiveStartDate: "string",
//     Ethnicity : "string", 
//     FirstName : "string", 
//     Gender: "string", 
//     HireDate: "date",
//     HomeFaxAreaCode: "string", 
//     HomeFaxCountryCode: "string", 
//     HomeFaxExtension: "string", 
//     HomeFaxLegislationCode: "string", 
//     HomeFaxNumber: "string", 
//     HomePhoneAreaCode: "string", 
//     HomePhoneCountryCode: "string", 
//     HomePhoneExtension: "string ",
//     HomePhoneLegislationCode: "string ",
//     HomePhoneNumber: "string ",
//     Honors: "string ",
//     LastName: "string ",
//     LastUpdateDate: "string(date-time) ",
//     LegalEntityId: "integer(int64) ",
//     LicenseNumber: "string ",
//     links: "array ",
//     MaritalStatus: "string ",
//     MiddleName: "string ",
//     MilitaryVetStatus: "string ",
//     NameSuffix: "string ",
//     NationalId: "string ",
//     NationalIdCountry: "string"
// }
// ]




// let data = [{
//     AddressLine:{
//         AddressLine1 : "string", 
//         AddressLine2 : "string", 
//         AddressLine3 : "string"
//     }
//     assignments: "array",
//     CitizenshipId: "integer(int64)", 
//     CitizenshipLegislationCode: "string",
//     CitizenshipStatus: "string",
//     CitizenshipToDate: "string(date)" 
//     City: "string", 
//     CorrespondenceLanguage: "string", 
//     Country: "string", 
//     CreationDate: "string", 
//     DateOfBirth: "string", 
//     directReports: "array", 
//     DisplayName: "string",
//     DriversLicense:{
//         DriversLicenseExpirationDate: "string", 
//         DriversLicenseIssuingCountry: "string", 
//         DriversLicenseId: "integer" 
//     }, 
//     EffectiveStartDate: "string",
//     Ethnicity : "string", 
//     FirstName : "string", 
//     Gender: "string", 
//     HireDate: "date",
//     home:{
//         HomeFaxAreaCode: "string", 
//         HomeFaxCountryCode: "string", 
//         HomeFaxExtension: "string", 
//         HomeFaxLegislationCode: "string", 
//         HomeFaxNumber: "string", 
//         HomePhoneAreaCode: "string", 
//         HomePhoneCountryCode: "string", 
//         HomePhoneExtension: "string ",
//         HomePhoneLegislationCode: "string ",
//         HomePhoneNumber: "string ",
//     },
//     Honors: "string ",
//     LastName: "string ",
//     LastUpdateDate: "string(date-time) ",
//     LegalEntityId: "integer(int64) ",
//     LicenseNumber: "string ",
//     links: "array ",
//     MaritalStatus: "string ",
//     MiddleName: "string ",
//     MilitaryVetStatus: "string ",
//     NameSuffix: "string ",
//     NationalId: "string ",
//     NationalIdCountry: "string",
// }]

